from __future__ import annotations

import atexit
import http.cookiejar
import sys
import urllib.request
from pathlib import Path
from typing import Any

from .credentials import credentials_to_netscape, get_config_dir, get_auth_toml_path, read_credentials

_CLIPVAULT_AUTH_SENTINEL = "__clipvault_auth__"
_COOKIE_FILE_NAME = "netscape_cookies.txt"

_cached_clipvault_cookie_path: Path | None = None


def clear_cookie_cache() -> None:
    """Delete the cached Netscape cookie file and reset the cache."""
    global _cached_clipvault_cookie_path
    if _cached_clipvault_cookie_path is not None:
        try:
            _cached_clipvault_cookie_path.unlink(missing_ok=True)
        except OSError:
            pass
        _cached_clipvault_cookie_path = None


atexit.register(clear_cookie_cache)


def resolve_cookies_path(cookies: Any) -> Path | None:
    if not cookies:
        return None
    if cookies == _CLIPVAULT_AUTH_SENTINEL or cookies is True:
        return _resolve_clipvault_auth()
    path = Path(cookies)
    if not path.is_file():
        raise RuntimeError(
            f"cookies file not found: {path}. "
            "Use 'clipvault auth login' to store credentials, "
            "or provide a valid Netscape cookies file path."
        )
    return path


def _resolve_clipvault_auth() -> Path:
    """Read ClipVault's own auth.toml and synthesize a Netscape cookies file (cached)."""
    global _cached_clipvault_cookie_path
    if _cached_clipvault_cookie_path is not None and _cached_clipvault_cookie_path.is_file():
        return _cached_clipvault_cookie_path

    auth_toml = get_auth_toml_path()
    if not auth_toml.is_file():
        raise RuntimeError(
            f"ClipVault auth file not found at {auth_toml}. "
            "Use 'clipvault auth login' to store credentials."
        )

    credentials = read_credentials()
    if not credentials:
        raise RuntimeError(
            f"No credentials found in {auth_toml}. "
            "Use 'clipvault auth login' to store credentials."
        )

    # Write to config dir instead of system temp — controlled lifecycle
    path = get_config_dir() / _COOKIE_FILE_NAME
    path.write_text(
        _format_netscape_cookies(credentials),
        encoding="utf-8",
    )
    _cached_clipvault_cookie_path = path
    print(f"[auth] using ClipVault credentials from {auth_toml}", file=sys.stderr)
    return _cached_clipvault_cookie_path


def _format_netscape_cookies(credentials: dict[str, dict[str, str]]) -> str:
    lines: list[str] = [
        "# Netscape HTTP Cookie File",
        "# Generated by ClipVault from auth.toml",
    ]
    for platform, creds in credentials.items():
        for line in credentials_to_netscape(platform, creds):
            lines.append(line)
    return "\n".join(lines) + "\n"


def apply_ytdlp_cookies(opts: dict[str, Any], cookies: Any) -> None:
    path = resolve_cookies_path(cookies)
    if path is None:
        return
    opts["cookiefile"] = str(path)
    print(f"[auth] cookies file: {path}", file=sys.stderr)


def build_authenticated_opener(cookies: Any = None) -> urllib.request.OpenerDirector:
    handlers: list[Any] = [urllib.request.ProxyHandler({})]
    path = resolve_cookies_path(cookies)
    if path is not None:
        jar = http.cookiejar.MozillaCookieJar(str(path))
        try:
            jar.load(ignore_discard=True, ignore_expires=True)
        except (http.cookiejar.LoadError, OSError) as exc:
            raise RuntimeError(f"failed to load cookies file {path}: {exc}") from exc
        handlers.append(urllib.request.HTTPCookieProcessor(jar))
        print(f"[auth] cookies loaded for HTTP requests: {path}", file=sys.stderr)
    return urllib.request.build_opener(*handlers)
