from __future__ import annotations

import atexit
import http.cookiejar
import urllib.request
from pathlib import Path
from typing import Any

from .credentials import credentials_to_netscape, get_config_dir, get_auth_toml_path, read_credentials
from .runtime_logs import emit_log

_CLIPVAULT_AUTH_SENTINEL = "__clipvault_auth__"
_COOKIE_FILE_NAME = "netscape_cookies.txt"

_cached_clipvault_cookie_path: Path | None = None


def clear_cookie_cache() -> None:
    """Delete the cached Netscape cookie file and reset the cache."""
    global _cached_clipvault_cookie_path
    if _cached_clipvault_cookie_path is not None:
        try:
            _cached_clipvault_cookie_path.unlink(missing_ok=True)
        except OSError:
            pass
        _cached_clipvault_cookie_path = None


atexit.register(clear_cookie_cache)


def resolve_cookies_path(cookies: Any) -> Path | None:
    if not cookies:
        return None
    if cookies == _CLIPVAULT_AUTH_SENTINEL or cookies is True:
        return _resolve_clipvault_auth()
    path = Path(cookies)
    if not path.is_file():
        raise RuntimeError(
            f"未找到 cookies 文件：{path}。"
            "请先运行 `clipvault auth login` 保存凭据，"
            "或提供有效的 Netscape cookies 文件路径。"
        )
    return path


def _resolve_clipvault_auth() -> Path:
    """Read ClipVault's own auth.toml and synthesize a Netscape cookies file (cached)."""
    global _cached_clipvault_cookie_path
    if _cached_clipvault_cookie_path is not None and _cached_clipvault_cookie_path.is_file():
        return _cached_clipvault_cookie_path

    auth_toml = get_auth_toml_path()
    if not auth_toml.is_file():
        raise RuntimeError(
            f"未找到 ClipVault 凭据文件：{auth_toml}。"
            "请先运行 `clipvault auth login` 保存凭据。"
        )

    credentials = read_credentials()
    if not credentials:
        raise RuntimeError(
            f"在 {auth_toml} 中未找到任何凭据。"
            "请先运行 `clipvault auth login` 保存凭据。"
        )

    # Write to config dir instead of system temp — controlled lifecycle
    path = get_config_dir() / _COOKIE_FILE_NAME
    path.write_text(
        _format_netscape_cookies(credentials),
        encoding="utf-8",
    )
    _cached_clipvault_cookie_path = path
    emit_log("auth", f"已从 ClipVault 凭据文件生成临时 cookies：{auth_toml}")
    return _cached_clipvault_cookie_path


def _format_netscape_cookies(credentials: dict[str, dict[str, str]]) -> str:
    lines: list[str] = [
        "# Netscape HTTP Cookie File",
        "# Generated by ClipVault from auth.toml",
    ]
    for platform, creds in credentials.items():
        for line in credentials_to_netscape(platform, creds):
            lines.append(line)
    return "\n".join(lines) + "\n"


def apply_ytdlp_cookies(opts: dict[str, Any], cookies: Any) -> None:
    path = resolve_cookies_path(cookies)
    if path is None:
        return
    opts["cookiefile"] = str(path)
    emit_log("auth", f"已启用 cookies 文件：{path}")


def build_authenticated_opener(cookies: Any = None) -> urllib.request.OpenerDirector:
    handlers: list[Any] = [urllib.request.ProxyHandler({})]
    path = resolve_cookies_path(cookies)
    if path is not None:
        jar = http.cookiejar.MozillaCookieJar(str(path))
        try:
            jar.load(ignore_discard=True, ignore_expires=True)
        except (http.cookiejar.LoadError, OSError) as exc:
            raise RuntimeError(f"加载 cookies 文件失败：{path}（{exc}）") from exc
        handlers.append(urllib.request.HTTPCookieProcessor(jar))
        emit_log("auth", f"HTTP 请求已加载 cookies：{path}")
    return urllib.request.build_opener(*handlers)
