from __future__ import annotations

import http.cookiejar
import os
import sys
import tempfile
import urllib.request
from pathlib import Path
from typing import Any

from .credentials import credentials_to_netscape, get_auth_toml_path, read_credentials

_cached_clipvault_cookie_path: Path | None = None


def resolve_cookies_path(cookies: Any) -> Path | None:
    if not cookies:
        return None
    return _resolve_clipvault_auth()


def _resolve_clipvault_auth() -> Path:
    """Read ClipVault's own auth.toml and synthesize a Netscape cookies file (cached)."""
    global _cached_clipvault_cookie_path
    if _cached_clipvault_cookie_path is not None and _cached_clipvault_cookie_path.is_file():
        return _cached_clipvault_cookie_path

    auth_toml = get_auth_toml_path()
    if not auth_toml.is_file():
        raise RuntimeError(
            f"ClipVault auth file not found at {auth_toml}. "
            "Use 'clipvault auth login' to store credentials."
        )

    credentials = read_credentials()
    if not credentials:
        raise RuntimeError(
            f"No credentials found in {auth_toml}. "
            "Use 'clipvault auth login' to store credentials."
        )

    fd, path = tempfile.mkstemp(prefix="clipvault_auth_", suffix=".txt", text=True)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by ClipVault from auth.toml\n")
        for platform, creds in credentials.items():
            for line in credentials_to_netscape(platform, creds):
                f.write(f"{line}\n")
    _cached_clipvault_cookie_path = Path(path)
    print(f"[auth] using ClipVault credentials from {auth_toml}", file=sys.stderr)
    return _cached_clipvault_cookie_path


def apply_ytdlp_cookies(opts: dict[str, Any], cookies: Any) -> None:
    path = resolve_cookies_path(cookies)
    if path is None:
        return
    opts["cookiefile"] = str(path)
    print(f"[auth] cookies file: {path}", file=sys.stderr)


def build_authenticated_opener(cookies: Any = None) -> urllib.request.OpenerDirector:
    handlers: list[Any] = [urllib.request.ProxyHandler({})]
    path = resolve_cookies_path(cookies)
    if path is not None:
        jar = http.cookiejar.MozillaCookieJar(str(path))
        try:
            jar.load(ignore_discard=True, ignore_expires=True)
        except (http.cookiejar.LoadError, OSError) as exc:
            raise RuntimeError(f"failed to load cookies file {path}: {exc}") from exc
        handlers.append(urllib.request.HTTPCookieProcessor(jar))
        print(f"[auth] cookies loaded for HTTP requests: {path}", file=sys.stderr)
    return urllib.request.build_opener(*handlers)
